In [5]:
import numpy as np

In [8]:
a=np.array([1,2,3,4,5,6])
print(a)

[1 2 3 4 5 6]


In [9]:
print(a)

[1 2 3 4 5 6]


In [10]:
b = np.arange(20)
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [12]:
c=np.zeros(7)
print(c)

[0. 0. 0. 0. 0. 0. 0.]


In [13]:
d=np.ones(5)
print(d)

[1. 1. 1. 1. 1.]


In [17]:
e = np.linspace(0, 10,6)
print(e)

[ 0.  2.  4.  6.  8. 10.]


In [19]:
f=np.eye(4)
print(f)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [8]:
g=np.random.rand(6)
print(g)

[0.93178426 0.96732236 0.31214982 0.75708591 0.10732923 0.62788004]


In [27]:
h=np.random.randn(6)
print(h)

[-1.19803686 -0.61316848  0.22684478  0.58698347 -1.43089021  1.21976385]


In [42]:
i=np.random.randint(1,6,5)
print(i)

[2 2 1 5 1]


In [48]:
j = np.arange(15).reshape(3,5)
print(j)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [50]:
k=np.random.rand(14)
print(k)
print("MAX:",np.max(k))

[0.1764853  0.81282801 0.95270106 0.16267473 0.44236493 0.47500155
 0.66186448 0.23964522 0.90876648 0.81800815 0.66921384 0.59654703
 0.6270032  0.87433002]
MAX: 0.9527010612219246


In [51]:
k=np.random.rand(14)
print(k)
print("MAX:",np.min(k))

[0.43026181 0.51011743 0.43050136 0.2180291  0.65384358 0.2836183
 0.9388448  0.64773017 0.63555248 0.07585034 0.92121437 0.34045012
 0.7501983  0.37470561]
MAX: 0.0758503421260085


In [61]:
l = np.arange(15).reshape(3,5)
print(l)
print(np.argmax(l))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
14


In [62]:
m = np.arange(15).reshape(3,5)
print(m)
print(np.argmin(m))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
0


In [63]:
n=np.array([1,2,3,4,5,6],dtype=float)
print(n)

[1. 2. 3. 4. 5. 6.]


In [69]:
o = np.array([[1,2,3,8],[4,5,6,9],[4,5,6,9]])
print(o.shape)

(3, 4)
